server {
  listen 5192;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml text/plain application/xml;
  gzip_min_length 1024;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
}